package com.askdata.platform.multitask.contract;

public enum MultitaskErrorCode {
    DAG_INVALID, PERMISSION_DENIED, PLAN_VERSION_CONFLICT, PLAN_CONFIRMATION_REQUIRED,
    TASK_NOT_RETRYABLE, EXECUTION_QUEUE_FULL, TASK_DEPENDENCY_FAILED, TASK_TIMEOUT,
    EVIDENCE_INCOMPLETE
}
