<script setup lang="ts">
import {computed,onMounted,ref} from 'vue';import {useRouter} from 'vue-router';import {adminApi,type JsonObject} from './admin-api';import {isOffline} from './runtime';
type Item={id:string;label:string};type Group={id:string;label:string;icon:string;children?:Item[]};
const menus:Group[]=[
 {id:'home',label:'首页',icon:'H'},
 {id:'permission',label:'权限管理',icon:'R',children:[{id:'roles',label:'角色管理'},{id:'accounts',label:'账号管理'},{id:'permissions',label:'权限配置'}]},
 {id:'assets',label:'资产管理',icon:'A',children:[{id:'metrics',label:'指标字典'},{id:'dimensions',label:'维度字典'},{id:'recommendations',label:'推荐词库'},{id:'mappings',label:'字段映射'}]},
 {id:'process',label:'流程配置',icon:'P',children:[{id:'intent',label:'意图规则'},{id:'sql-templates',label:'SQL模板'},{id:'conversation',label:'会话配置'},{id:'parameters',label:'参数校验'},{id:'layers',label:'七层配置'}]},
 {id:'scenes',label:'场景管理',icon:'S',children:[{id:'scenarios',label:'标准场景'},{id:'shortcuts',label:'快捷按钮'},{id:'dashboards',label:'驾驶舱'},{id:'fixtures',label:'Fixture'}]},
 {id:'logs',label:'日志管理',icon:'L',children:[{id:'sessions',label:'会话记录'},{id:'requests',label:'执行轨迹'},{id:'sql',label:'SQL审计'},{id:'audit',label:'操作日志'}]},
 {id:'compliance',label:'合规管控',icon:'C',children:[{id:'sensitive',label:'涉密管控'},{id:'limits',label:'访问限流'},{id:'masking',label:'数据脱敏'},{id:'intercepts',label:'拦截话术'}]},
 {id:'operations',label:'运维配置',icon:'O',children:[{id:'interface',label:'界面配置'},{id:'system',label:'系统参数'},{id:'readiness',label:'就绪检查'},{id:'recovery',label:'备份与重置'}]},
 {id:'models',label:'大模型配置',icon:'M'},{id:'datasources',label:'数据源配置',icon:'D'},
 {id:'mock',label:'Mock管理',icon:'K',children:[{id:'mock-data',label:'模拟数据'},{id:'demo-switch',label:'演示开关'},{id:'wording',label:'话术维护'}]}
];
const router=useRouter(),collapsed=ref(false),expanded=ref(new Set(['permission'])),active=ref('home'),tabs=ref<Item[]>([{id:'home',label:'首页'}]),config=ref<JsonObject>({}),ready=ref<JsonObject>({}),rows=ref<JsonObject[]>([]),busy=ref(false),message=ref(''),dirty=ref(false),draft=ref<JsonObject>(),filter=ref(''),selected=ref<JsonObject>();
const phase2Profiles=ref<JsonObject[]>([]),phase2Json=ref(JSON.stringify({name:'Phase 2 Profile',datasource_type:'CLICKHOUSE',model_base_url:'https://model.example/v1',model:'model-name',model_api_key:'',datasource_url:'https://clickhouse.example:8443',datasource_username:'default',datasource_password:'',database:'default',allowed_tables:['dws_loan_aggr_wide'],timeout:30,retries:2},null,2));
const labels=computed(()=>Object.fromEntries(menus.flatMap(x=>[{id:x.id,label:x.label},...(x.children||[])]).map(x=>[x.id,x.label]))),title=computed(()=>labels.value[active.value]||'管理页面');
function toggle(g:Group){if(!g.children){open({id:g.id,label:g.label});return}const next=new Set(expanded.value);next.has(g.id)?next.delete(g.id):next.add(g.id);expanded.value=next}
async function open(item:Item){active.value=item.id;if(!tabs.value.some(x=>x.id===item.id))tabs.value.push(item);message.value='';if(['sessions','requests','sql','audit'].includes(item.id))await loadLogs()}
function close(id:string){if(id==='home')return;tabs.value=tabs.value.filter(x=>x.id!==id);if(active.value===id)open(tabs.value.at(-1)!)}
function changed(){dirty.value=true;message.value='存在未保存变更'}
function updateList(target:JsonObject,key:string,event:Event){target[key]=(event.target as HTMLInputElement).value.split(/[，,]/).map(x=>x.trim()).filter(Boolean);changed()}
function addValue(list:any[]){list.push('新条目');changed()}function removeValue(list:any[],index:number){list.splice(index,1);changed()}
async function inspect(row:JsonObject){try{selected.value=await adminApi.logDetail(active.value,row.id)}catch(e){message.value=String(e)}}
function exportRows(){const blob=new Blob([JSON.stringify(rows.value,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${active.value}-logs.json`;a.click();URL.revokeObjectURL(a.href)}
async function loadLogs(){busy.value=true;try{rows.value=(await adminApi.logs(active.value,filter.value)).items}catch(e){message.value=String(e)}finally{busy.value=false}}
async function save(){busy.value=true;try{const saved=await adminApi.saveDraft(`管理端草稿 ${new Date().toLocaleString()}`,config.value);draft.value=saved;dirty.value=false;message.value=`草稿 v${saved.version} 已保存，尚未影响活动会话`}catch(e){message.value=String(e)}finally{busy.value=false}}
async function publish(){if(!draft.value)return message.value='请先保存草稿';busy.value=true;try{await adminApi.publish(draft.value.id);message.value='发布成功，仅新建 Session 使用新版本';draft.value=undefined}catch(e){message.value=String(e)}finally{busy.value=false}}
async function provider(kind:string){try{message.value=JSON.stringify(await adminApi.testProvider(kind))}catch(e){message.value=String(e)}}
async function createPhase2(){busy.value=true;try{const created=await adminApi.createPhase2Profile(JSON.parse(phase2Json.value));await adminApi.enablePhase2Profile(created.id);const result=await adminApi.diagnosePhase2Profile(created.id);phase2Profiles.value=(await adminApi.phase2Profiles()).items;message.value=`已加密保存并启用，诊断：${result.status}`}catch(e){message.value=String(e)}finally{busy.value=false}}
async function recovery(action:string){try{message.value=action==='backup'?JSON.stringify(await adminApi.backup()):JSON.stringify(await adminApi.reset(action));if(action==='official')config.value=await adminApi.baseline()}catch(e){message.value=String(e)}}
function download(){const blob=new Blob([JSON.stringify(config.value,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='askdata-config.json';a.click();URL.revokeObjectURL(a.href)}
onMounted(async()=>{try{[config.value,ready.value]=await Promise.all([adminApi.baseline(),adminApi.readiness()]);if(!isOffline)phase2Profiles.value=(await adminApi.phase2Profiles()).items;config.value.compliance??={sensitive_words:['身份证','明细','涉密'],intercept_message:'涉密或明细数据已按合规规则拦截',max_rows:200,masking:true};config.value.system??={title:'智能银行问数平台',welcome:'今天想了解什么经营数据？',default_role:'admin',simulation_speed:120,show_trace:true}}catch(e){message.value=String(e)}});
</script>
<template><div class="admin-shell"><aside class="admin-sidebar" :class="{collapsed}"><div class="side-logo"><b>N</b><span>NLQ后台</span></div><button class="collapse" @click="collapsed=!collapsed">⇋</button><div class="menu-list"><div v-for="g in menus" :key="g.id" class="menu-group"><button class="menu-parent" :class="{active:active===g.id||g.children?.some(x=>x.id===active)}" @click="toggle(g)"><i>{{g.icon}}</i><span>{{g.label}}</span><em v-if="g.children">{{expanded.has(g.id)?'▼':'▶'}}</em></button><div v-if="g.children&&expanded.has(g.id)" class="sub-menu"><button v-for="item in g.children" :key="item.id" :class="{active:active===item.id}" @click="open(item)">{{item.label}}<small v-if="item.id==='accounts'">三期</small></button></div></div></div></aside>
<div class="admin-main"><header class="admin-top"><button @click="router.push('/')">← 返回用户问数</button><span class="mode">{{isOffline?'OFFLINE':'POC'}}</span><span>🔔</span><b>管理员 admin</b></header><div class="tabs"><button v-for="tab in tabs" :key="tab.id" :class="{active:active===tab.id}" @click="open(tab)">{{tab.label}} <i v-if="tab.id!=='home'" @click.stop="close(tab.id)">×</i></button><a @click="tabs=[tabs[0]];open(tabs[0])">全部关闭标签</a></div>
<main class="admin-content"><div class="page-title"><div><small>Phase 1 管理控制台</small><h1>{{title}}</h1></div><div class="toolbar"><span v-if="message" class="message">{{message}}</span><button @click="download">导出 JSON</button><button @click="save" :disabled="busy">保存草稿</button><button class="primary" @click="publish" :disabled="busy||!draft">发布</button></div></div>
<section v-if="active==='home'||active==='readiness'" class="grid"><article><small>系统状态</small><strong>{{ready.ready?'已就绪':'未就绪'}}</strong><p>三角色、八场景和双 Provider 验证</p></article><article><small>角色</small><strong>{{config.roles?.length||0}}</strong><p>权限快照与会话版本隔离</p></article><article><small>标准场景</small><strong>{{config.scenarios?.length||0}}</strong><p>全角色默认用例完整性</p></article><div class="panel wide"><h3>完整性检查</h3><p :class="{ok:config.roles?.length===3}">✓ 角色数量：{{config.roles?.length||0}} / 3</p><p :class="{ok:config.scenarios?.length===8}">✓ 场景数量：{{config.scenarios?.length||0}} / 8</p><p>✓ 七层顺序固定为 L1—L7，不允许在管理端重排</p></div></section>
<section v-else-if="['roles','permissions'].includes(active)" class="panel"><h3>角色与权限</h3><div v-for="role in config.roles" :key="role.id" class="role-card"><div><input v-model="role.name" @input="changed"><code>{{role.id}}</code><label><input type="checkbox" v-model="role.enabled" @change="changed">启用</label></div><label>可访问机构<input :value="role.orgs.join(', ')" @change="updateList(role,'orgs',$event)"></label><label>可查询指标<input :value="role.metrics.join(', ')" @change="updateList(role,'metrics',$event)"></label><label>功能权限<input :value="role.features.join(', ')" @change="updateList(role,'features',$event)"></label></div></section>
<section v-else-if="active==='accounts'" class="panel empty"><h3>账号管理</h3><p>账号登录、SSO 与密码管理属于三期企业版范围；一期不伪造账号功能。</p></section>
<section v-else-if="['metrics','dimensions'].includes(active)" class="panel"><h3>{{title}}</h3><div class="dictionary"><div v-for="(value,i) in config.assets[active]" :key="i"><input v-model="config.assets[active][i]" @input="changed"><button class="danger" @click="removeValue(config.assets[active],i)">删除</button></div><button @click="addValue(config.assets[active])">新增{{title}}</button></div></section>
<section v-else-if="active==='recommendations'" class="panel"><h3>推荐词库</h3><div v-for="role in config.roles" :key="role.id" class="role-card"><b>{{role.name}}</b><label>推荐问句（逗号分隔）<input :value="config.assets.recommendations[role.id].join(', ')" @change="updateList(config.assets.recommendations,role.id,$event)"></label></div></section>
<section v-else-if="['mappings','sql-templates','intent','conversation','parameters','layers'].includes(active)" class="panel"><h3>{{title}}</h3><label>模拟数仓表<input v-model="config.assets.table" disabled></label><label>参数化 SQL 模板<textarea class="field-area" v-model="config.assets.sql_template" @input="changed"></textarea></label><p>一期只允许只读官方宽表、参数绑定和固定 L1—L7 顺序；不允许任意表名、DDL/DML 或层重排。</p></section>
<section v-else-if="['sensitive','limits','masking','intercepts'].includes(active)" class="panel"><h3>{{title}}</h3><label>涉密词（逗号分隔）<input :value="config.compliance.sensitive_words.join(', ')" @change="updateList(config.compliance,'sensitive_words',$event)"></label><label>最大返回行数<input type="number" v-model.number="config.compliance.max_rows" @input="changed"></label><label><input type="checkbox" v-model="config.compliance.masking" @change="changed">启用基础脱敏</label><label>拦截话术<textarea class="field-area" v-model="config.compliance.intercept_message" @input="changed"></textarea></label></section>
<section v-else-if="['interface','system','demo-switch','wording'].includes(active)" class="panel"><h3>{{title}}</h3><label>页面标题<input v-model="config.system.title" @input="changed"></label><label>欢迎语<input v-model="config.system.welcome" @input="changed"></label><label>默认角色<select v-model="config.system.default_role" @change="changed"><option v-for="role in config.roles" :value="role.id">{{role.name}}</option></select></label><label>模拟速度（毫秒）<input type="number" min="0" max="3000" v-model.number="config.system.simulation_speed" @input="changed"></label><label><input type="checkbox" v-model="config.system.show_trace" @change="changed">显示执行轨迹</label></section>
<section v-else-if="active==='scenarios'||['shortcuts','dashboards','fixtures'].includes(active)" class="panel"><h3>场景、用例与轮次</h3><details v-for="scene in config.scenarios" :key="scene.id"><summary><b>0{{scene.number}} {{scene.name}}</b><span>{{scene.cases.length}} 个角色用例</span></summary><div v-for="c in scene.cases" :key="c.id" class="case"><b>{{c.role_id}}</b><div v-for="turn in c.turns" :key="turn.turn"><input v-model="turn.question" @input="changed"><select v-model="turn.expected_status" @change="changed"><option>SUCCEEDED</option><option>SHORT_CIRCUITED</option><option>BLOCKED</option><option>WAITING_INPUT</option></select><input v-model="turn.expected_last_layer" @input="changed"></div></div></details></section>
<section v-else-if="['sessions','requests','sql','audit'].includes(active)" class="panel"><div class="log-tools"><select v-model="filter"><option value="">全部状态</option><option>SUCCEEDED</option><option>BLOCKED</option><option>FAILED</option></select><button @click="loadLogs">筛选/刷新</button><button @click="exportRows">导出 JSON</button><span>{{rows.length}} 条</span></div><div class="table-wrap"><table><thead><tr><th v-for="k in Object.keys(rows[0]||{})" :key="k">{{k}}</th></tr></thead><tbody><tr v-for="(row,i) in rows" :key="i" @click="inspect(row)"><td v-for="(value,k) in row" :key="k"><code>{{typeof value==='string'&&value.length>100?value.slice(0,100)+'…':value}}</code></td></tr></tbody></table><p v-if="!rows.length" class="empty">暂无记录</p></div><pre v-if="selected" class="log-detail">{{JSON.stringify(selected,null,2)}}</pre></section>
<section v-else-if="active==='models'||active==='datasources'" class="panel"><h3>Provider 状态</h3><div v-for="p in active==='models'?['mock','openai-compatible']:['sqlite','clickhouse','mysql']" :key="p" class="provider"><b>{{p}}</b><span :class="{ok:['mock','sqlite'].includes(p)}">{{['mock','sqlite'].includes(p)?'READY':(isOffline?'POC 中配置':'PHASE 2')}}</span><button @click="provider(p)">{{['mock','sqlite'].includes(p)?'健康检查':'查看能力'}}</button></div><template v-if="!isOffline"><h3>Phase 2 Profile</h3><p>凭据仅提交到服务端加密保存，不会在列表、日志或导出中回显。</p><textarea class="field-area" v-model="phase2Json" aria-label="Phase 2 Provider JSON"></textarea><button class="primary" @click="createPhase2" :disabled="busy">加密保存、启用并诊断</button><div v-for="profile in phase2Profiles" :key="profile.id" class="provider"><b>{{profile.name}}</b><span :class="{ok:profile.status==='ENABLED'}">{{profile.status}}</span><code>{{profile.datasource_type}}</code></div></template><p v-else>Offline Demo 永远不连接真实 Provider。</p></section>
<section v-else-if="active==='recovery'" class="panel"><h3>备份与重置</h3><div class="actions"><button @click="recovery('backup')">创建备份</button><button @click="recovery('official')">恢复官方配置</button><button class="danger" @click="recovery('mock-data')">重置 Mock 数据</button></div><p>官方快照不可删除或覆盖。恢复和重置操作会写入操作审计。</p></section>
<section v-else class="panel editor"><h3>{{title}}</h3><p>以下配置随草稿统一校验、保存和发布；发布只影响新 Session。</p><textarea :value="JSON.stringify(config,null,2)" @change="config=JSON.parse(($event.target as HTMLTextAreaElement).value);changed()"></textarea></section>
</main></div></div></template>
