<script setup lang="ts">
import {computed,nextTick,onMounted,ref} from 'vue';import {useRouter} from 'vue-router';import type {Adapter,RoleId,Session,QueryDetail} from './types';import {PocApiAdapter} from './adapters/poc';import {OfflineAdapter} from './adapters/offline';
type TraceEvent=Record<string,any>;type Turn={id:string;question:string;scene:number;sceneName:string;role:RoleId;events:TraceEvent[];detail?:QueryDetail;error?:string;running:boolean;streamedAnswer?:string;displayText:string;outputQueue:string[];typing:boolean;waiting:boolean;waitTimer?:number};
const router=useRouter(),offline=location.protocol==='file:'||new URLSearchParams(location.search).has('offline'),adapter:Adapter=offline?new OfflineAdapter():new PocApiAdapter();
const roles=[['admin','张总｜总行行长（全机构+全指标权限）'],['beijing','李总｜分行行长（北京分行权限）'],['retail','王总｜业务负责人（零售信贷业务权限）']] as const;
const scenes=['基础查数（机构/指标权限）','BI驾驶舱跳转','模糊问句兜底推荐','同比归因分析','越权权限拦截','多轮上下文追问','缺失参数交互式补全','纯取数+二次归因连贯会话'];
const defaults:Record<RoleId,string[]>={admin:['2026年3月上海分行对公贷款投放金额','查看全行经营指标分析大盘','查一下2026年3月银行贷款相关数据','2026年3月北京分行贷款投放同比去年变化','查询客户身份证号和贷款明细','2026年3月北京分行零售贷款投放金额','查询贷款投放同比数据','2026年3月全行对公贷款投放金额'],beijing:['2026年3月北京分行对公贷款投放金额','查看北京分行经营指标分析大盘','查一下2026年3月北京分行贷款相关数据','2026年3月北京分行贷款投放同比去年变化','查询上海分行2026年3月对公贷款数据','2026年3月北京分行零售贷款投放金额','查询贷款投放同比数据','2026年3月北京分行对公贷款投放金额'],retail:['2026年3月全行零售贷款投放金额','查看零售信贷专项经营驾驶舱','查一下2026年3月零售贷款相关数据','2026年3月全行零售贷款同比去年变化','查询2026年3月对公贷款投放','2026年3月全行零售贷款投放金额','查询零售贷款同比数据','2026年3月全行零售贷款投放金额']};
const layerNames:Record<string,string>={L1:'交互层',L2:'对话理解层',L3:'语义层',L4:'数据资产层',L5:'查询生成层',L6:'执行层',L7:'问数解读层'};
const role=ref<RoleId>('admin'),session=ref<Session>(),question=ref(''),active=ref(0),turns=ref<Turn[]>([]),parent=ref<string>(),executionMode=ref('PHASE1_DEMO'),providerProfiles=ref<any[]>([]),providerProfileId=ref(''),sessionError=ref(''),chat=ref<HTMLElement>();
const currentRole=computed(()=>roles.find(x=>x[0]===role.value)?.[1]),running=computed(()=>turns.value.some(x=>x.running));
async function scroll(){await nextTick();if(chat.value)chat.value.scrollTop=chat.value.scrollHeight}
async function loadProfiles(){if(!offline){providerProfiles.value=(await adapter.admin('/phase2/providers')).items;const available=providerProfiles.value.filter(x=>x.selectable);if(!available.some(x=>x.id===providerProfileId.value))providerProfileId.value=available[0]?.id||''}}
async function newSession(){sessionError.value='';session.value=undefined;try{if(executionMode.value.startsWith('PHASE2')&&!providerProfileId.value)throw new Error('没有可用的二期Provider Profile。请在后台新增真实模型与数据源连接，执行诊断并启用。');session.value=await adapter.createSession(role.value,offline?{}:{execution_mode:executionMode.value,provider_profile_id:executionMode.value.startsWith('PHASE2')?providerProfileId.value:undefined});parent.value=undefined}catch(e){sessionError.value=String(e)}}
async function roleChanged(){turns.value=[];await newSession();turns.value.push({id:'notice-'+Date.now(),question:'',scene:0,sceneName:'系统提示',role:role.value,events:[{type:'notice',output:{message:'已切换演示角色，聊天界面与权限缓存已清空，旧会话记录仍保留。'}}],running:false,displayText:'已切换演示角色，聊天界面与权限缓存已清空，旧会话记录仍保留。',outputQueue:[],typing:false,waiting:false})}
function sceneClick(i:number){active.value=i;question.value=defaults[role.value][i];run(question.value,i)}
const terminalStates=new Set(['SUCCEEDED','FAILED','BLOCKED','SHORT_CIRCUITED','WAITING_INPUT','PARTIAL_SUCCESS','CANCELLED']);
async function watchTerminal(id:string,turn:Turn){for(let i=0;i<120&&turn.running;i++){await new Promise(r=>setTimeout(r,500));try{const detail=await adapter.detail(id);if(terminalStates.has(String(detail.request.status))){turn.detail=detail;turn.running=false;await scroll();return}}catch{}}}
function clearLayerWait(t:Turn){if(t.waitTimer)window.clearTimeout(t.waitTimer);t.waitTimer=undefined;t.waiting=false}
function armLayerWait(t:Turn){clearLayerWait(t);t.waitTimer=window.setTimeout(()=>{if(t.running)t.waiting=true;scroll()},3000)}
async function drainOutput(t:Turn){if(t.typing)return;t.typing=true;while(t.outputQueue.length){const chunk=t.outputQueue.shift()||'';for(const char of chunk){t.displayText+=char;await new Promise(r=>setTimeout(r,12));if(t.displayText.length%8===0)scroll()}}t.typing=false;await scroll()}
function enqueueOutput(t:Turn,text:string){if(!text)return;t.outputQueue.push(text);void drainOutput(t)}
function layerTranscript(t:Turn,e:TraceEvent){const completed=t.events.filter(x=>x.type==='layer.completed').length;const prefix=completed>1?'\n\n':'';const result=e.layer_code==='L7'?'解读已完成，正在流式生成最终答复…':outputText(e);return `${prefix}✓ ${e.layer_code} ${layerNames[e.layer_code]}  ·  ${e.status}\n${result}`}
async function run(text=question.value,scene=active.value){if(!session.value||!text.trim()||running.value)return;active.value=scene;question.value='';turns.value.push({id:'pending-'+Date.now(),question:text,scene:scene+1,sceneName:scenes[scene],role:role.value,events:[],running:true,streamedAnswer:'',displayText:'',outputQueue:[],typing:false,waiting:false});const turn=turns.value[turns.value.length-1];await scroll();try{const id=await adapter.query(session.value.id,text,'scenario-'+(scene+1),parent.value);turn.id=id;parent.value=id;void watchTerminal(id,turn);await adapter.events(id,e=>{turn.events.push(e as TraceEvent);if(e.type==='layer.started')armLayerWait(turn);if(e.type==='layer.completed'){clearLayerWait(turn);enqueueOutput(turn,layerTranscript(turn,e as TraceEvent))}if(e.type==='answer.delta'){const delta=String(e.delta||'');turn.streamedAnswer=(turn.streamedAnswer||'')+delta;enqueueOutput(turn,delta)}if(e.type==='request.completed'||e.type==='request.cancelled'){clearLayerWait(turn);turn.running=false}scroll()});turn.detail=await adapter.detail(id)}catch(e){clearLayerWait(turn);turn.error=String(e)}finally{clearLayerWait(turn);turn.running=false;await scroll()}}
async function stop(){const t=turns.value.find(x=>x.running);if(t&&!t.id.startsWith('pending-'))await adapter.cancel(t.id)}
function outputText(e:TraceEvent){const o=e.output||{};if(o.message)return o.message;if(o.answer)return o.answer;if(o.normalized_question)return '标准化问句：'+o.normalized_question;if(o.parameters)return '识别参数：'+JSON.stringify(o.parameters);if(o.dashboard)return '匹配驾驶舱：'+o.dashboard;if(o.table||o.metric)return '选定资产：'+[o.provider,o.table,o.metric].filter(Boolean).join(' / ');if(o.queries)return '生成 '+o.queries.length+' 条参数化SQL';if(o.row_count!==undefined)return '返回 '+o.row_count+' 行，来源：'+(o.sources||[]).join(',');return JSON.stringify(o)}
function terminalOutput(t:Turn){return (t.detail?.layers.at(-1)?.output||{}) as any}
function dashboardItems(t:Turn){const configured=terminalOutput(t).dashboards;if(configured?.length)return configured;return t.role==='admin'?[{name:'总行行长经营驾驶舱',url:'/dashboards/head-office.html'}]:t.role==='beijing'?[{name:'分行行长经营驾驶舱',url:'/dashboards/branch-president.html'}]:[{name:'业务负责人专项驾驶舱',url:'/dashboards/business-owner.html'}]}
function resultText(t:Turn){const o=terminalOutput(t);if(t.scene===2)return '根据当前角色权限，为您匹配可访问的经营大盘：';return t.streamedAnswer||o.answer||o.message||t.detail?.request.status||''}
function chartSpec(t:Turn){return terminalOutput(t).chart||null}function chartRows(t:Turn){const spec=chartSpec(t),rows=t.detail?.result||[];if(!spec||!rows.length)return[];const series=(spec.series||[]).filter((key:string)=>rows.some((r:any)=>Number(r[key])));return rows.flatMap((row:any)=>series.map((key:string)=>({label:`${row[spec.category_field]||row.org_name||'结果'}·${key==='previous_value'?'同期':'本期'}`,value:Number(row[key]||0)})))}function chartWidth(t:Turn,value:number){const max=Math.max(1,...chartRows(t).map(x=>Math.abs(x.value)));return Math.max(5,Math.abs(value)/max*100)+'%'}
function optionQuery(t:Turn,value:string){const base=terminalOutput(t).options||[];const chosen=value.includes('2026')?'2026年3月':value;const org=chosen.includes('分行')||chosen==='全行'?chosen:(base.find((x:string)=>x.includes('分行')||x==='全行')||'全行');const metric=chosen.includes('贷款')?chosen:'贷款投放';return [chosen.includes('2026')?chosen:'2026年3月',org,metric].join('，')}
function guideScene(text:string,current:number){if(text.includes('驾驶舱'))return 1;if(text.includes('同比'))return 3;return current-1}
function layerInput(t:Turn,e:TraceEvent){if(e.layer_code==='L1')return '原始问句：'+t.question;if(e.layer_code==='L2')return '标准化问句 + 当前角色权限快照：'+currentRole.value;if(e.layer_code==='L3')return '已识别业务参数与意图';if(e.layer_code==='L4')return '语义计划与已发布资产配置';if(e.layer_code==='L5')return '受控资产映射与SQL模板';if(e.layer_code==='L6')return '参数化SQL计划';return 'L6实际执行结果'}
onMounted(async()=>{await loadProfiles();await newSession()});
</script>
<template><div class="ask-page"><header class="ask-header"><div class="ask-title">NLQ智能银行问数平台｜多角色权限全场景演示</div><div class="header-controls"><button @click="router.push('/admin')">后台管理</button><select v-if="!offline" v-model="executionMode" @change="newSession"><option>PHASE1_DEMO</option><option>PHASE2_DEMO</option><option>PHASE2_POC</option></select><select v-if="!offline&&executionMode.startsWith('PHASE2')" v-model="providerProfileId" @change="newSession"><option value="" disabled>请选择可用Profile</option><option v-for="p in providerProfiles.filter(x=>x.selectable)" :value="p.id">{{p.name}}（{{p.diagnostic_status}}）</option></select><span>当前演示身份：</span><select v-model="role" @change="roleChanged"><option v-for="r in roles" :value="r[0]">{{r[1]}}</option></select></div></header><div v-if="sessionError" class="session-error">{{sessionError}}</div>
<div ref="chat" class="chat-wrap"><div v-if="!turns.length" class="welcome-bubble"><b>您好，{{currentRole}}</b><p>请选择下方8大场景，或直接输入自然语言问题。</p><small>{{offline?'Offline Demo 本地模拟':'POC 七层真实执行'}} · 每层完成后将在聊天区实时输出具体轨迹</small></div>
<div v-for="t in turns" :key="t.id" class="conversation-turn"><div v-if="t.question" class="msg-item user-msg"><div class="user-bubble">{{t.question}}</div></div>
<div v-if="t.displayText||t.running||t.waiting" class="msg-item ai-msg"><div class="ai-bubble unified-trace-bubble"><div class="unified-trace-head"><span>AskData AI</span></div><div class="stream-transcript">{{t.displayText}}<i v-if="t.typing" class="typing-cursor"></i></div><div v-if="t.waiting" class="layer-wait"><i></i><span>这一层需要多一点时间，正在认真处理…</span></div></div></div>
<div v-if="t.detail" class="msg-item ai-msg"><div class="ai-bubble result-bubble"><span class="scene-tag">场景{{t.scene}}执行结果</span><b class="stream-answer">{{resultText(t)}}<i v-if="t.running" class="typing-cursor"></i></b><div v-if="t.scene===2" class="dashboard-result"><p>✅ 已识别经营大盘跳转意图，语义层短路数据查询链路</p><a v-for="x in dashboardItems(t)" :href="x.url" target="_blank" rel="noopener" class="dashboard-link">🔗 {{x.name}}</a><p v-if="t.role==='beijing'" class="role-filter">已自动过滤总行/其他分行驾驶舱权限</p><p v-if="t.role==='retail'" class="role-filter">已自动过滤对公业务驾驶舱权限</p></div><div v-if="chartRows(t).length" class="result-chart"><h4>{{chartSpec(t)?.title}}</h4><div v-for="bar in chartRows(t)" class="result-chart-row"><span>{{bar.label}}</span><i><b :style="{width:chartWidth(t,bar.value)}"></b></i><strong>{{bar.value.toLocaleString()}}</strong></div></div><table v-if="t.detail.result.length"><thead><tr><th v-for="(_,k) in t.detail.result[0]">{{k}}</th></tr></thead><tbody><tr v-for="r in t.detail.result"><td v-for="v in r">{{v}}</td></tr></tbody></table><div v-if="!t.detail.sql_executions?.length" class="no-sql">未执行SQL：当前请求在{{t.detail.request.last_layer||'前置层'}}短路/拦截/等待输入，未访问数据源。</div><details v-if="t.detail.sql_executions?.length"><summary>接口SQL日志（{{t.detail.sql_executions.length}}条）</summary><pre>{{JSON.stringify(t.detail.sql_executions,null,2)}}</pre></details><div v-if="terminalOutput(t).guides?.length" class="guide-box"><span>您还可以继续问：</span><button v-for="x in terminalOutput(t).guides" @click="run(x,guideScene(x,t.scene))">{{x}}</button></div><div v-if="terminalOutput(t).recommendations?.length" class="option-row"><button v-for="x in terminalOutput(t).recommendations" @click="run(x,t.scene-1)">{{x}}</button></div><div v-if="terminalOutput(t).options?.length" class="option-row"><button v-for="x in terminalOutput(t).options" @click="run(optionQuery(t,x),t.scene-1)">{{x}}</button></div></div></div><div v-if="t.error" class="msg-item ai-msg"><div class="ai-bubble error">{{t.error}}</div></div></div></div>
<div class="quick-chat-bar"><div class="quick-chat-title">🔥 8大标准演示场景（一键Demo）</div><div class="quick-chat-buttons"><button v-for="(s,i) in scenes" :class="{selected:active===i}" @click="sceneClick(i)">场景{{i+1}}：{{s}}</button></div></div>
<div class="input-footer"><button class="voice-btn" @click="question='2026年3月各分行零售贷款同比变化'">🎤</button><input v-model="question" :disabled="!session" @keydown.enter="run()" placeholder="输入自然语言提问，支持8大场景、多轮追问、权限校验"><button v-if="running" class="stop" @click="stop">停止执行</button><button v-else :disabled="!session" @click="run()">发送提问</button></div></div></template>
