<script setup lang="ts">
import {computed,onMounted,ref} from 'vue';import {useRoute,useRouter} from 'vue-router';import type {Adapter,RoleId,Session,QueryDetail} from './types';import {PocApiAdapter} from './adapters/poc';import {OfflineAdapter} from './adapters/offline';
const route=useRoute(),router=useRouter(),offline=location.protocol==='file:'||new URLSearchParams(location.search).has('offline');const adapter:Adapter=offline?new OfflineAdapter():new PocApiAdapter();
const roles=[['admin','张总｜总行领导'],['beijing','李总｜北京分行'],['retail','王总｜零售主管']] as const;const scenes=['基础查数','BI 驾驶舱','模糊推荐','同比归因','权限合规拦截','多轮上下文','参数补全','二次归因'];
const defaults:Record<RoleId,string[]>= {admin:['2026年3月上海分行对公贷款投放金额','查看全行经营指标分析大盘','查一下2026年3月银行贷款相关数据','2026年3月北京分行贷款投放同比去年变化','查询客户身份证号和贷款明细','2026年3月北京分行零售贷款投放金额','查询贷款投放同比数据','2026年3月全行对公贷款投放金额'],beijing:['2026年3月北京分行对公贷款投放金额','查看北京分行经营指标分析大盘','查一下2026年3月北京分行贷款相关数据','2026年3月北京分行贷款投放同比去年变化','查询上海分行2026年3月对公贷款数据','2026年3月北京分行零售贷款投放金额','查询贷款投放同比数据','2026年3月北京分行对公贷款投放金额'],retail:['2026年3月全行零售贷款投放金额','查看零售信贷专项经营驾驶舱','查一下2026年3月零售贷款相关数据','2026年3月全行零售贷款同比去年变化','查询2026年3月对公贷款投放','2026年3月全行零售贷款投放金额','查询零售贷款同比数据','2026年3月全行零售贷款投放金额']};
const role=ref<RoleId>('admin'),session=ref<Session>(),question=ref(''),active=ref(0),busy=ref(false),events=ref<Record<string,unknown>[]>([]),detail=ref<QueryDetail>(),error=ref(''),parent=ref<string>();const isAdmin=computed(()=>route.path.startsWith('/admin'));const technical=ref(false);const ready=ref<Record<string,unknown>>();
async function newSession(){session.value=await adapter.createSession(role.value);events.value=[];detail.value=undefined;parent.value=undefined}async function roleChanged(){await newSession()}async function run(text?:string){if(!session.value)return;question.value=text||question.value;if(!question.value.trim())return;busy.value=true;error.value='';events.value=[];detail.value=undefined;try{const id=await adapter.query(session.value.id,question.value,`scenario-${active.value+1}`,parent.value);parent.value=id;await adapter.events(id,e=>events.value.push(e));detail.value=await adapter.detail(id)}catch(e){error.value=String(e)}finally{busy.value=false}}async function stop(){if(parent.value)await adapter.cancel(parent.value)}async function follow(text:string){question.value=text;await run()}onMounted(async()=>{await newSession();ready.value=await adapter.readiness()});
</script>
<template><div class="app"><header><div class="brand"><span class="logo">数</span><div><b>智能银行问数平台</b><small>七层可信 NLQ · {{adapter.mode}}</small></div></div><nav><button :class="{active:!isAdmin}" @click="router.push('/')">用户问数</button><button :class="{active:isAdmin}" @click="router.push('/admin')">后台管理</button></nav><select v-model="role" @change="roleChanged" aria-label="演示角色"><option v-for="r in roles" :value="r[0]">{{r[1]}}</option></select></header>
<main v-if="!isAdmin"><aside><h3>八大演示场景</h3><button v-for="(s,i) in scenes" :class="{picked:active===i}" @click="active=i;question=defaults[role][i]"><span>0{{i+1}}</span>{{s}}</button><div class="notice">{{offline?'离线模拟执行，数据保存在本浏览器':'POC 真实七层执行与 SQLite 查询'}}</div></aside><section class="workspace"><div class="hero"><p>您好，{{roles.find(r=>r[0]===role)?.[1]}}</p><h1>今天想了解什么经营数据？</h1></div><div class="chips"><button v-for="(s,i) in scenes" @click="active=i;run(defaults[role][i])">{{s}}</button></div><div v-if="events.length" class="trace"><div class="trace-head"><b>执行轨迹</b><label v-if="!offline"><input type="checkbox" v-model="technical"> 技术详情</label></div><div class="steps"><div v-for="e in events.filter(x=>x.type==='layer.completed')" class="step"><i>✓</i><span>{{e.layer_code}}</span><small>{{e.status}}</small></div></div></div><div v-if="detail" class="answer"><b>问数结果</b><p>{{(detail.layers.at(-1)?.output as any)?.answer||detail.request.status}}</p><table v-if="detail.result.length"><thead><tr><th v-for="(_,k) in detail.result[0]">{{k}}</th></tr></thead><tbody><tr v-for="r in detail.result"><td v-for="v in r">{{v}}</td></tr></tbody></table><div v-if="detail.request.status==='WAITING_INPUT'" class="chips"><button @click="follow('2026年3月，全行贷款投放')">2026年3月 · 全行</button></div><pre v-if="technical">{{JSON.stringify(detail,null,2)}}</pre></div><p class="error" v-if="error">{{error}}</p><div class="composer"><textarea v-model="question" @keydown.ctrl.enter="run()" placeholder="输入经营数据问题…" aria-label="问数输入"></textarea><button v-if="busy" class="stop" @click="stop">停止</button><button v-else @click="run()">发送</button></div></section></main>
<main v-else class="admin"><aside><h3>系统管理</h3><button v-for="x in ['角色与权限','数据资产','七层流程','场景用例','日志与审计','合规规则','Provider','备份与重置']">{{x}}</button></aside><section class="workspace"><div class="admin-title"><div><small>Phase 1 管理控制台</small><h1>演示就绪中心</h1></div><span class="badge">{{ready?.ready?'已就绪':'检查中'}}</span></div><div class="cards"><article><small>角色</small><strong>{{ready?.roles||3}}</strong><p>权限快照与会话隔离</p></article><article><small>标准场景</small><strong>{{ready?.scenarios||8}}</strong><p>全角色默认用例</p></article><article><small>配置版本</small><strong>v1</strong><p>Official Demo Baseline</p></article></div><div class="panel"><h3>Provider 状态</h3><div class="row"><span>Mock Model</span><b>READY</b></div><div class="row"><span>SQLite 模拟数仓</span><b>READY</b></div><div class="row"><span>OpenAI / ClickHouse / MySQL</span><em>二期支持</em></div></div><div class="panel"><h3>配置生命周期</h3><p>所有编辑先保存为草稿；发布与回滚只影响新 Session。官方快照不可删除、不可原地覆盖。</p><div class="actions"><button>复制为草稿</button><button>导出 JSON</button><button>恢复官方配置</button></div></div></section></main></div></template>
