<script setup lang="ts">
import {onMounted,ref} from 'vue';import {useRouter} from 'vue-router';import type {Adapter,RoleId,Session,QueryDetail} from './types';import {PocApiAdapter} from './adapters/poc';import {OfflineAdapter} from './adapters/offline';import {isOffline as offline} from './runtime';import {adminApi} from './admin-api';
const router=useRouter();const adapter:Adapter=offline?new OfflineAdapter():new PocApiAdapter();
const roles=ref<Array<[RoleId,string]>>([['admin','张总｜总行领导'],['beijing','李总｜北京分行'],['retail','王总｜零售主管']]);const scenes=ref(['基础查数','BI 驾驶舱','模糊推荐','同比归因','权限合规拦截','多轮上下文','参数补全','二次归因']);
const defaults=ref<Record<RoleId,string[]>>({admin:[],beijing:[],retail:[]});
const role=ref<RoleId>('admin'),session=ref<Session>(),question=ref(''),active=ref(0),busy=ref(false),events=ref<Record<string,unknown>[]>([]),detail=ref<QueryDetail>(),error=ref(''),parent=ref<string>();const technical=ref(false),settings=ref({title:'智能银行问数平台',welcome:'今天想了解什么经营数据？',show_trace:true});
async function newSession(){session.value=await adapter.createSession(role.value);events.value=[];detail.value=undefined;parent.value=undefined}async function roleChanged(){await newSession()}async function run(text?:string){if(!session.value)return;question.value=text||question.value;if(!question.value.trim())return;busy.value=true;error.value='';events.value=[];detail.value=undefined;try{const id=await adapter.query(session.value.id,question.value,`scenario-${active.value+1}`,parent.value);parent.value=id;await adapter.events(id,e=>events.value.push(e));detail.value=await adapter.detail(id)}catch(e){error.value=String(e)}finally{busy.value=false}}async function stop(){if(parent.value)await adapter.cancel(parent.value)}async function follow(text:string){question.value=text;await run()}onMounted(async()=>{const config=await adminApi.baseline();settings.value={...settings.value,...config.system};roles.value=config.roles.map((x:any)=>[x.id,x.name]) as Array<[RoleId,string]>;scenes.value=config.scenarios.map((x:any)=>x.name);for(const id of ['admin','beijing','retail'] as RoleId[])defaults.value[id]=config.scenarios.map((scene:any)=>scene.cases.find((c:any)=>c.role_id===id)?.turns[0]?.question||'');role.value=config.system?.default_role||'admin';await newSession()});
</script>
<template><div class="app"><header><div class="brand"><span class="logo">数</span><div><b>{{settings.title}}</b><small>七层可信 NLQ · {{adapter.mode}}</small></div></div><nav><button :class="{active:true}" @click="router.push('/')">用户问数</button><button @click="router.push('/admin')">后台管理</button></nav><select v-model="role" @change="roleChanged" aria-label="演示角色"><option v-for="r in roles" :value="r[0]">{{r[1]}}</option></select></header>
<main><aside><h3>八大演示场景</h3><button v-for="(s,i) in scenes" :class="{picked:active===i}" @click="active=i;question=defaults[role][i]"><span>0{{i+1}}</span>{{s}}</button><div class="notice">{{offline?'离线模拟执行，数据保存在本浏览器':'POC 真实七层执行与 SQLite 查询'}}</div></aside><section class="workspace"><div class="hero"><p>您好，{{roles.find(r=>r[0]===role)?.[1]}}</p><h1>{{settings.welcome}}</h1></div><div class="chips"><button v-for="(s,i) in scenes" @click="active=i;run(defaults[role][i])">{{s}}</button></div><div v-if="events.length&&settings.show_trace" class="trace"><div class="trace-head"><b>执行轨迹</b><label v-if="!offline"><input type="checkbox" v-model="technical"> 技术详情</label></div><div class="steps"><div v-for="e in events.filter(x=>x.type==='layer.completed')" class="step"><i>✓</i><span>{{e.layer_code}}</span><small>{{e.status}}</small></div></div></div><div v-if="detail" class="answer"><b>问数结果</b><p>{{(detail.layers.at(-1)?.output as any)?.answer||detail.request.status}}</p><table v-if="detail.result.length"><thead><tr><th v-for="(_,k) in detail.result[0]">{{k}}</th></tr></thead><tbody><tr v-for="r in detail.result"><td v-for="v in r">{{v}}</td></tr></tbody></table><div v-if="detail.request.status==='WAITING_INPUT'" class="chips"><button @click="follow('2026年3月，全行贷款投放')">2026年3月 · 全行</button></div><pre v-if="technical">{{JSON.stringify(detail,null,2)}}</pre></div><p class="error" v-if="error">{{error}}</p><div class="composer"><textarea v-model="question" @keydown.ctrl.enter="run()" placeholder="输入经营数据问题…" aria-label="问数输入"></textarea><button v-if="busy" class="stop" @click="stop">停止</button><button v-else @click="run()">发送</button></div></section></main>
</div></template>
