ALTER TABLE ai_secret_ref ADD COLUMN revision_no INTEGER NOT NULL DEFAULT 1;

CREATE TABLE ai_secret_rotation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    secret_ref_id BIGINT NOT NULL REFERENCES ai_secret_ref(id),
    from_fingerprint CHAR(64) NOT NULL,
    to_fingerprint CHAR(64) NOT NULL,
    from_key_version VARCHAR(32),
    to_key_version VARCHAR(32),
    rotated_by BIGINT,
    rotated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ai_model_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    provider_type VARCHAR(32) NOT NULL,
    endpoint VARCHAR(512) NOT NULL,
    model_name VARCHAR(128) NOT NULL,
    model_version VARCHAR(64),
    temperature DECIMAL(4,3) NOT NULL DEFAULT 0,
    top_p DECIMAL(4,3) NOT NULL DEFAULT 1,
    secret_ref_id BIGINT REFERENCES ai_secret_ref(id),
    timeout_seconds DECIMAL(6,2) NOT NULL DEFAULT 30,
    max_tokens INTEGER NOT NULL DEFAULT 4096,
    context_window INTEGER NOT NULL DEFAULT 8192,
    structured_output BOOLEAN NOT NULL DEFAULT TRUE,
    retry_count INTEGER NOT NULL DEFAULT 1,
    max_concurrency INTEGER NOT NULL DEFAULT 10,
    last_diagnostic_status VARCHAR(20),
    last_diagnostic_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT','ENABLED','DISABLED')),
    version_no INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ai_model_capability (
    model_profile_id BIGINT NOT NULL REFERENCES ai_model_profile(id),
    capability VARCHAR(32) NOT NULL,
    layer_code VARCHAR(4),
    prompt_template VARCHAR(100000),
    output_schema_json VARCHAR(100000),
    safety_prompt VARCHAR(100000),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY(model_profile_id, capability)
);

CREATE TABLE ai_model_rate_limit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_profile_id BIGINT NOT NULL REFERENCES ai_model_profile(id),
    scope_type VARCHAR(20) NOT NULL,
    scope_id BIGINT,
    per_minute INTEGER NOT NULL,
    per_day INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ENABLED','DISABLED')),
    UNIQUE(model_profile_id, scope_type, scope_id)
);

CREATE TABLE ai_runtime_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    model_profile_id BIGINT NOT NULL REFERENCES ai_model_profile(id),
    data_source_id BIGINT NOT NULL REFERENCES meta_data_source(id),
    execution_mode VARCHAR(20) NOT NULL CHECK (execution_mode IN ('DEMO','POC','PROD')),
    fixture_fallback BOOLEAN NOT NULL DEFAULT FALSE,
    default_parameters_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT','ENABLED','DISABLED')),
    version_no INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE ai_runtime_profile ADD CONSTRAINT ck_runtime_fixture_mode CHECK (execution_mode = 'DEMO' OR fixture_fallback = FALSE);

ALTER TABLE meta_data_source ADD COLUMN last_diagnostic_status VARCHAR(20);
ALTER TABLE meta_data_source ADD COLUMN last_diagnostic_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE ai_provider_diagnostic (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_type VARCHAR(32) NOT NULL CHECK (resource_type IN ('MODEL_PROFILE','DATA_SOURCE')),
    resource_id BIGINT NOT NULL,
    resource_version INTEGER NOT NULL,
    provider_type VARCHAR(32) NOT NULL,
    result VARCHAR(20) NOT NULL CHECK (result IN ('SUCCEEDED','FAILED')),
    result_code VARCHAR(64) NOT NULL,
    message VARCHAR(1000),
    latency_ms BIGINT,
    checked_by BIGINT,
    checked_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_provider_diagnostic_resource ON ai_provider_diagnostic(resource_type, resource_id, checked_at);
