ALTER TABLE run_request ADD COLUMN synced_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE run_layer_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES run_request(id) ON DELETE CASCADE,
    sequence_no SMALLINT NOT NULL,
    layer_code VARCHAR(4) NOT NULL,
    status VARCHAR(32) NOT NULL,
    input_json VARCHAR(1000000) NOT NULL,
    output_json VARCHAR(1000000),
    provider VARCHAR(128),
    elapsed_ms DECIMAL(14,3),
    error_code VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(request_id, sequence_no),
    UNIQUE(request_id, layer_code)
);
CREATE INDEX idx_run_layer_created ON run_layer_execution(created_at, id);

CREATE TABLE run_sql_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES run_request(id) ON DELETE CASCADE,
    sequence_no SMALLINT NOT NULL,
    business_sql VARCHAR(1000000) NOT NULL,
    actual_sql_masked VARCHAR(1000000) NOT NULL,
    parameters_json VARCHAR(1000000) NOT NULL,
    source VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    row_count BIGINT,
    elapsed_ms DECIMAL(14,3),
    error_code VARCHAR(128),
    fallback BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(request_id, sequence_no)
);
CREATE INDEX idx_run_sql_created ON run_sql_execution(created_at, id);

CREATE TABLE run_provider_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES run_request(id) ON DELETE CASCADE,
    provider_kind VARCHAR(20) NOT NULL CHECK (provider_kind IN ('MODEL','DATA_SOURCE','FIXTURE')),
    layer_code VARCHAR(4) NOT NULL,
    provider VARCHAR(128) NOT NULL,
    sequence_no SMALLINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    elapsed_ms DECIMAL(14,3),
    row_count BIGINT,
    error_code VARCHAR(128),
    fallback BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(request_id, provider_kind, layer_code, sequence_no)
);
CREATE INDEX idx_run_provider_created ON run_provider_execution(created_at, id);

CREATE TABLE run_sse_event (
    request_id BIGINT NOT NULL REFERENCES run_request(id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    payload_json VARCHAR(1000000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY(request_id, event_id)
);
CREATE INDEX idx_run_sse_created ON run_sse_event(created_at, request_id, event_id);

CREATE TABLE run_result_snapshot (
    request_id BIGINT PRIMARY KEY REFERENCES run_request(id) ON DELETE CASCADE,
    payload_json VARCHAR(1000000) NOT NULL,
    masked BOOLEAN NOT NULL CHECK (masked = TRUE),
    size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
    classification_level VARCHAR(20) NOT NULL CHECK (classification_level IN ('PUBLIC','INTERNAL','SENSITIVE','SECRET','RESTRICTED')),
    storage_type VARCHAR(20) NOT NULL DEFAULT 'INLINE' CHECK (storage_type IN ('INLINE','OBJECT_STORAGE')),
    storage_uri VARCHAR(1000),
    content_hash CHAR(64) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_run_result_expiry ON run_result_snapshot(expires_at, classification_level);

CREATE TABLE ops_retention_policy (
    fact_type VARCHAR(64) PRIMARY KEY,
    online_days INTEGER NOT NULL CHECK (online_days BETWEEN 1 AND 3650),
    archive_before_delete BOOLEAN NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO ops_retention_policy(fact_type,online_days,archive_before_delete) VALUES
 ('RUN_SSE_EVENT',30,FALSE),('RUN_RESULT_SNAPSHOT',90,FALSE),('RUN_LAYER_EXECUTION',180,TRUE),
 ('RUN_SQL_EXECUTION',180,TRUE),('RUN_PROVIDER_EXECUTION',180,TRUE),('RUN_REQUEST',180,TRUE),('RUN_SESSION',180,TRUE);

CREATE TABLE run_fact_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_table VARCHAR(64) NOT NULL,
    source_id VARCHAR(128) NOT NULL,
    request_public_id VARCHAR(36),
    payload_json VARCHAR(1000000) NOT NULL,
    original_created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    archived_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(source_table, source_id)
);
CREATE INDEX idx_run_archive_source_time ON run_fact_archive(source_table, original_created_at, id);
