CREATE TABLE ops_alert_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    metric_code VARCHAR(64) NOT NULL,
    comparison_operator VARCHAR(4) NOT NULL CHECK (comparison_operator IN ('GT','GTE','LT','LTE')),
    threshold_value DOUBLE PRECISION NOT NULL,
    minimum_samples INTEGER NOT NULL DEFAULT 1 CHECK (minimum_samples >= 0),
    severity VARCHAR(16) NOT NULL CHECK (severity IN ('INFO','WARNING','CRITICAL')),
    cooldown_seconds INTEGER NOT NULL DEFAULT 300 CHECK (cooldown_seconds >= 1),
    adapter_code VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ops_alert_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id BIGINT NOT NULL REFERENCES ops_alert_rule(id),
    trace_id VARCHAR(128) NOT NULL,
    metric_code VARCHAR(64) NOT NULL,
    observed_value DOUBLE PRECISION NOT NULL,
    sample_count INTEGER NOT NULL CHECK (sample_count >= 0),
    threshold_value DOUBLE PRECISION NOT NULL,
    severity VARCHAR(16) NOT NULL,
    delivery_adapter VARCHAR(32) NOT NULL,
    delivery_status VARCHAR(20) NOT NULL CHECK (delivery_status IN ('PENDING','DELIVERED','DELIVERY_FAILED')),
    delivery_error_code VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivered_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_ops_alert_event_rule_created ON ops_alert_event(rule_id, created_at DESC);
CREATE INDEX idx_ops_alert_event_status_created ON ops_alert_event(delivery_status, created_at DESC);

INSERT INTO ops_alert_rule(code,name,metric_code,comparison_operator,threshold_value,minimum_samples,severity,cooldown_seconds,adapter_code) VALUES
('execution-queue-high','执行队列积压','execution.queue.depth','GTE',40,1,'WARNING',300,'configured'),
('execution-failure-ratio','执行失败率过高','execution.failure.ratio','GTE',0.20,5,'CRITICAL',300,'configured'),
('provider-failure-ratio','Provider失败率过高','provider.failure.ratio','GTE',0.20,5,'CRITICAL',300,'configured'),
('sql-failure-ratio','SQL失败率过高','sql.failure.ratio','GTE',0.20,5,'CRITICAL',300,'configured'),
('publish-failure-count','配置发布失败','config.publish.failure.count','GTE',1,1,'CRITICAL',300,'configured');
