CREATE TABLE run_task_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL UNIQUE,
    request_id BIGINT NOT NULL REFERENCES run_request(id) ON DELETE CASCADE,
    plan_version INTEGER NOT NULL CHECK (plan_version > 0),
    status VARCHAR(32) NOT NULL CHECK (status IN ('DRAFT','VALIDATED','WAITING_CONFIRMATION','CONFIRMED','EXECUTING','COMPLETED','CANCELLED','INVALID')),
    plan_json VARCHAR(1000000) NOT NULL,
    completeness_policy VARCHAR(64) NOT NULL,
    permission_snapshot_id VARCHAR(128) NOT NULL,
    config_release_id BIGINT NOT NULL REFERENCES cfg_release(id),
    created_by VARCHAR(128) NOT NULL,
    confirmed_by VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMP WITH TIME ZONE,
    UNIQUE(request_id, plan_version)
);
CREATE INDEX idx_run_task_plan_request_status ON run_task_plan(request_id, status, plan_version);

CREATE TABLE run_task_node (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL UNIQUE,
    plan_id BIGINT NOT NULL REFERENCES run_task_plan(id) ON DELETE CASCADE,
    node_code VARCHAR(64) NOT NULL,
    node_type VARCHAR(32) NOT NULL CHECK (node_type IN ('SQL','CALCULATION','SUMMARY')),
    critical BOOLEAN NOT NULL,
    status VARCHAR(32) NOT NULL CHECK (status IN ('WAITING','READY','QUEUED','RUNNING','RETRY_WAIT','SUCCEEDED','FAILED','SKIPPED','CANCELLATION_REQUESTED','CANCELLED','TIMED_OUT')),
    input_json VARCHAR(1000000) NOT NULL,
    output_schema_json VARCHAR(1000000) NOT NULL,
    timeout_ms BIGINT NOT NULL CHECK (timeout_ms BETWEEN 1000 AND 1800000),
    max_attempts INTEGER NOT NULL CHECK (max_attempts BETWEEN 1 AND 10),
    capability_version VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(plan_id, node_code)
);
CREATE INDEX idx_run_task_node_plan_status ON run_task_node(plan_id, status, id);

CREATE TABLE run_task_dependency (
    plan_id BIGINT NOT NULL REFERENCES run_task_plan(id) ON DELETE CASCADE,
    upstream_node_id BIGINT NOT NULL REFERENCES run_task_node(id) ON DELETE CASCADE,
    downstream_node_id BIGINT NOT NULL REFERENCES run_task_node(id) ON DELETE CASCADE,
    dependency_type VARCHAR(20) NOT NULL CHECK (dependency_type IN ('SUCCESS','COMPLETION')),
    PRIMARY KEY(plan_id, upstream_node_id, downstream_node_id),
    CHECK (upstream_node_id <> downstream_node_id)
);
CREATE INDEX idx_run_task_dependency_downstream ON run_task_dependency(plan_id, downstream_node_id);

CREATE TABLE run_task_asset_binding (
    node_id BIGINT NOT NULL REFERENCES run_task_node(id) ON DELETE CASCADE,
    asset_type VARCHAR(32) NOT NULL,
    asset_id VARCHAR(128) NOT NULL,
    asset_version VARCHAR(64) NOT NULL,
    permission_decision_json VARCHAR(1000000) NOT NULL,
    data_as_of_rule VARCHAR(512),
    PRIMARY KEY(node_id, asset_type, asset_id)
);

CREATE TABLE run_task_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL UNIQUE,
    node_id BIGINT NOT NULL REFERENCES run_task_node(id) ON DELETE CASCADE,
    attempt_no INTEGER NOT NULL CHECK (attempt_no > 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING','RUNNING','SUCCEEDED','FAILED','CANCELLED','TIMED_OUT')),
    execution_id VARCHAR(128),
    error_code VARCHAR(64),
    retry_reason VARCHAR(1000),
    started_at TIMESTAMP WITH TIME ZONE,
    ended_at TIMESTAMP WITH TIME ZONE,
    UNIQUE(node_id, attempt_no)
);
CREATE INDEX idx_run_task_attempt_node_status ON run_task_attempt(node_id, status, attempt_no);

CREATE TABLE run_execution_fact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL UNIQUE,
    node_id BIGINT NOT NULL REFERENCES run_task_node(id) ON DELETE CASCADE,
    attempt_id BIGINT NOT NULL REFERENCES run_task_attempt(id),
    payload_json VARCHAR(1000000),
    storage_uri VARCHAR(1000),
    content_hash CHAR(64) NOT NULL,
    row_count BIGINT NOT NULL DEFAULT 0 CHECK (row_count >= 0),
    data_as_of VARCHAR(128) NOT NULL,
    class_level VARCHAR(20) NOT NULL CHECK (class_level IN ('PUBLIC','INTERNAL','SENSITIVE','SECRET','RESTRICTED')),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((payload_json IS NOT NULL AND storage_uri IS NULL) OR (payload_json IS NULL AND storage_uri IS NOT NULL)),
    UNIQUE(node_id, attempt_id)
);
CREATE INDEX idx_run_execution_fact_expiry ON run_execution_fact(expires_at, class_level);

CREATE TABLE run_answer_claim (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES run_request(id) ON DELETE CASCADE,
    answer_version INTEGER NOT NULL CHECK (answer_version > 0),
    claim_no INTEGER NOT NULL CHECK (claim_no > 0),
    claim_text VARCHAR(100000) NOT NULL,
    claim_type VARCHAR(32) NOT NULL,
    verified BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(request_id, answer_version, claim_no)
);

CREATE TABLE run_claim_evidence (
    claim_id BIGINT NOT NULL REFERENCES run_answer_claim(id) ON DELETE CASCADE,
    fact_id BIGINT NOT NULL REFERENCES run_execution_fact(id),
    PRIMARY KEY(claim_id, fact_id)
);

CREATE TABLE audit_plan_change (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES run_request(id) ON DELETE CASCADE,
    from_version INTEGER,
    to_version INTEGER NOT NULL CHECK (to_version > 0),
    actor VARCHAR(128) NOT NULL,
    change_json VARCHAR(1000000) NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_plan_change_request ON audit_plan_change(request_id, created_at, id);

ALTER TABLE run_request ADD COLUMN current_plan_id BIGINT REFERENCES run_task_plan(id);
ALTER TABLE run_request ADD COLUMN plan_status VARCHAR(32) CHECK (plan_status IN ('DRAFT','VALIDATED','WAITING_CONFIRMATION','CONFIRMED','EXECUTING','COMPLETED','CANCELLED','INVALID'));
ALTER TABLE run_request ADD COLUMN total_tasks INTEGER NOT NULL DEFAULT 0 CHECK (total_tasks >= 0);
ALTER TABLE run_request ADD COLUMN succeeded_tasks INTEGER NOT NULL DEFAULT 0 CHECK (succeeded_tasks >= 0);
ALTER TABLE run_request ADD COLUMN failed_tasks INTEGER NOT NULL DEFAULT 0 CHECK (failed_tasks >= 0);
ALTER TABLE run_request ADD COLUMN skipped_tasks INTEGER NOT NULL DEFAULT 0 CHECK (skipped_tasks >= 0);
ALTER TABLE run_request ADD COLUMN cancelled_tasks INTEGER NOT NULL DEFAULT 0 CHECK (cancelled_tasks >= 0);
ALTER TABLE run_request ADD COLUMN answer_version INTEGER NOT NULL DEFAULT 0 CHECK (answer_version >= 0);

ALTER TABLE run_sql_execution ADD COLUMN task_node_id BIGINT REFERENCES run_task_node(id);
ALTER TABLE run_sql_execution ADD COLUMN attempt_id BIGINT REFERENCES run_task_attempt(id);
CREATE INDEX idx_run_sql_task_attempt ON run_sql_execution(task_node_id, attempt_id);
ALTER TABLE run_provider_execution ADD COLUMN task_node_id BIGINT REFERENCES run_task_node(id);
ALTER TABLE run_provider_execution ADD COLUMN attempt_id BIGINT REFERENCES run_task_attempt(id);
CREATE INDEX idx_run_provider_task_attempt ON run_provider_execution(task_node_id, attempt_id);
ALTER TABLE run_sse_event ADD COLUMN task_node_id BIGINT REFERENCES run_task_node(id);
CREATE INDEX idx_run_sse_task_event ON run_sse_event(task_node_id, event_id);

INSERT INTO ops_retention_policy(fact_type,online_days,archive_before_delete) VALUES
 ('RUN_TASK_PLAN',180,TRUE),('RUN_TASK_NODE',180,TRUE),('RUN_TASK_ATTEMPT',180,TRUE),
 ('RUN_EXECUTION_FACT',90,TRUE),('RUN_ANSWER_CLAIM',180,TRUE),('AUDIT_PLAN_CHANGE',365,TRUE);
