CREATE TABLE platform_schema_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_version VARCHAR(32) NOT NULL,
    schema_status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO platform_schema_metadata(product_version, schema_status)
VALUES ('2.0.0-SNAPSHOT', 'BOOTSTRAPPED');
