CREATE TABLE cfg_release (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_no VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT','REVIEWING','PUBLISHED','ARCHIVED','ROLLED_BACK')),
    base_release_id BIGINT REFERENCES cfg_release(id),
    snapshot_json VARCHAR(1000000) NOT NULL,
    snapshot_hash CHAR(64) NOT NULL,
    change_summary VARCHAR(4000),
    published_by BIGINT,
    published_at TIMESTAMP WITH TIME ZONE,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_cfg_release_status_created ON cfg_release(status, created_at);

CREATE TABLE cfg_current_release (
    environment VARCHAR(20) PRIMARY KEY,
    release_id BIGINT NOT NULL REFERENCES cfg_release(id),
    updated_by BIGINT,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cfg_release_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_id BIGINT NOT NULL REFERENCES cfg_release(id),
    resource_type VARCHAR(64) NOT NULL,
    resource_id VARCHAR(128) NOT NULL,
    operation VARCHAR(20) NOT NULL CHECK (operation IN ('CREATE','UPDATE','DELETE')),
    before_json VARCHAR(1000000),
    after_json VARCHAR(1000000),
    content_hash CHAR(64) NOT NULL,
    UNIQUE(release_id, resource_type, resource_id)
);

CREATE TABLE ai_secret_ref (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    secret_type VARCHAR(32) NOT NULL,
    provider_type VARCHAR(32) NOT NULL,
    external_ref VARCHAR(512) NOT NULL,
    key_version VARCHAR(32),
    fingerprint CHAR(64) NOT NULL,
    rotated_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE','REVOKED','EXPIRED')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_secret_ref_status_expiry ON ai_secret_ref(status, expires_at);

CREATE TABLE iam_org (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT REFERENCES iam_org(id),
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    org_type VARCHAR(32) NOT NULL,
    path VARCHAR(1024) NOT NULL,
    level_no SMALLINT NOT NULL CHECK (level_no >= 0),
    sort_no INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ENABLED','DISABLED')),
    version_no INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_iam_org_parent_sort ON iam_org(parent_id, sort_no);

CREATE TABLE iam_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL UNIQUE,
    username VARCHAR(191) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    user_type VARCHAR(20) NOT NULL CHECK (user_type IN ('ADMIN','BUSINESS','SERVICE')),
    org_id BIGINT NOT NULL REFERENCES iam_org(id),
    identity_provider_code VARCHAR(64) NOT NULL,
    external_subject VARCHAR(191) NOT NULL,
    email VARCHAR(254),
    status VARCHAR(20) NOT NULL CHECK (status IN ('ENABLED','FROZEN','DISABLED')),
    permission_version BIGINT NOT NULL DEFAULT 1,
    version_no INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(identity_provider_code, external_subject)
);
CREATE INDEX idx_iam_user_org_status ON iam_user(org_id, status, id);
CREATE INDEX idx_iam_user_status_cursor ON iam_user(status, id);

CREATE TABLE iam_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    role_type VARCHAR(20) NOT NULL CHECK (role_type IN ('ADMIN','BUSINESS','SERVICE')),
    priority INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ENABLED','DISABLED')),
    version_no INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE iam_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT REFERENCES iam_permission(id),
    code VARCHAR(128) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    permission_type VARCHAR(20) NOT NULL CHECK (permission_type IN ('MENU','BUTTON','API','FEATURE')),
    resource_path VARCHAR(512),
    http_method VARCHAR(10),
    status VARCHAR(20) NOT NULL CHECK (status IN ('ENABLED','DISABLED'))
);

CREATE TABLE iam_user_role (
    user_id BIGINT NOT NULL REFERENCES iam_user(id),
    role_id BIGINT NOT NULL REFERENCES iam_role(id),
    valid_from TIMESTAMP WITH TIME ZONE,
    valid_to TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY(user_id, role_id)
);

CREATE TABLE iam_role_permission (
    role_id BIGINT NOT NULL REFERENCES iam_role(id),
    permission_id BIGINT NOT NULL REFERENCES iam_permission(id),
    effect VARCHAR(10) NOT NULL CHECK (effect IN ('ALLOW','DENY')),
    PRIMARY KEY(role_id, permission_id)
);

CREATE TABLE meta_data_source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    source_type VARCHAR(20) NOT NULL CHECK (source_type IN ('CLICKHOUSE','MYSQL','POSTGRESQL','SQLITE')),
    environment VARCHAR(20) NOT NULL CHECK (environment IN ('DEV','TEST','POC','PROD')),
    endpoint VARCHAR(512),
    database_name VARCHAR(128) NOT NULL,
    username VARCHAR(128) NOT NULL,
    credential_secret_id BIGINT REFERENCES ai_secret_ref(id),
    tls_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    read_only BOOLEAN NOT NULL DEFAULT TRUE CHECK (read_only = TRUE),
    max_rows INTEGER NOT NULL DEFAULT 1000 CHECK (max_rows BETWEEN 1 AND 10000),
    timeout_seconds DECIMAL(6,2) NOT NULL DEFAULT 30,
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT','ENABLED','DISABLED')),
    version_no INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE meta_data_table (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_source_id BIGINT NOT NULL REFERENCES meta_data_source(id),
    schema_name VARCHAR(128) NOT NULL,
    table_name VARCHAR(128) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    table_type VARCHAR(20) NOT NULL CHECK (table_type IN ('WIDE','DETAIL','DIMENSION','VIEW')),
    query_priority INTEGER NOT NULL DEFAULT 0,
    allowed BOOLEAN NOT NULL DEFAULT FALSE,
    classification_level VARCHAR(20) NOT NULL DEFAULT 'INTERNAL',
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT','ENABLED','DISABLED')),
    UNIQUE(data_source_id, schema_name, table_name)
);

CREATE TABLE meta_data_field (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT NOT NULL REFERENCES meta_data_table(id),
    field_name VARCHAR(128) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    data_type VARCHAR(64) NOT NULL,
    nullable BOOLEAN NOT NULL DEFAULT TRUE,
    field_role VARCHAR(20) NOT NULL CHECK (field_role IN ('METRIC','DIMENSION','TIME','ORG','KEY')),
    classification_level VARCHAR(20) NOT NULL CHECK (classification_level IN ('PUBLIC','INTERNAL','SENSITIVE','SECRET','RESTRICTED')),
    masking_required BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT','ENABLED','DISABLED')),
    UNIQUE(table_id, field_name)
);

CREATE TABLE meta_metric (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    business_definition VARCHAR(4000) NOT NULL,
    calculation_expression VARCHAR(4000) NOT NULL,
    unit VARCHAR(32) NOT NULL,
    aggregation_type VARCHAR(20) NOT NULL CHECK (aggregation_type IN ('SUM','AVG','MAX','MIN','RATIO','NONE')),
    owner_org_id BIGINT REFERENCES iam_org(id),
    classification_level VARCHAR(20) NOT NULL,
    detail_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT','ENABLED','DISABLED')),
    version_no INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE meta_dimension (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    dimension_type VARCHAR(32) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT','ENABLED','DISABLED'))
);

CREATE TABLE flow_parameter_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parameter_code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    data_type VARCHAR(32) NOT NULL,
    required_flag BOOLEAN NOT NULL DEFAULT FALSE,
    validation_regex VARCHAR(512),
    missing_prompt VARCHAR(1000),
    option_source VARCHAR(128),
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT','ENABLED','DISABLED'))
);

CREATE TABLE flow_sql_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    template_type VARCHAR(32) NOT NULL,
    sql_text VARCHAR(1000000) NOT NULL,
    dialect VARCHAR(32) NOT NULL,
    max_rows INTEGER NOT NULL CHECK (max_rows BETWEEN 1 AND 10000),
    timeout_seconds DECIMAL(6,2) NOT NULL,
    checksum CHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT','ENABLED','DISABLED')),
    version_no INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE flow_scenario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(500),
    terminal_layer VARCHAR(4) NOT NULL CHECK (terminal_layer IN ('L1','L2','L3','L4','L5','L6','L7')),
    default_metric_id BIGINT REFERENCES meta_metric(id),
    fallback_policy VARCHAR(20) NOT NULL CHECK (fallback_policy IN ('NONE','FIXTURE','AUDITED_FIXTURE')),
    sort_no INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT','ENABLED','DISABLED')),
    version_no INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE flow_scenario_param (
    scenario_id BIGINT NOT NULL REFERENCES flow_scenario(id),
    parameter_rule_id BIGINT NOT NULL REFERENCES flow_parameter_rule(id),
    required_override BOOLEAN,
    default_value_json VARCHAR(100000),
    sort_no INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY(scenario_id, parameter_rule_id)
);

CREATE TABLE flow_scenario_sql (
    scenario_id BIGINT NOT NULL REFERENCES flow_scenario(id),
    sql_template_id BIGINT NOT NULL REFERENCES flow_sql_template(id),
    sequence_no INTEGER NOT NULL CHECK (sequence_no > 0),
    purpose VARCHAR(128) NOT NULL,
    required_flag BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY(scenario_id, sequence_no),
    UNIQUE(scenario_id, sql_template_id)
);

CREATE TABLE audit_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(128) NOT NULL,
    actor_id BIGINT,
    actor_name_snapshot VARCHAR(128) NOT NULL,
    action VARCHAR(128) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    resource_id VARCHAR(128),
    before_json VARCHAR(1000000),
    after_json VARCHAR(1000000),
    client_ip VARCHAR(64),
    user_agent_hash CHAR(64),
    result VARCHAR(20) NOT NULL,
    error_code VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_trace ON audit_operation_log(trace_id);
CREATE INDEX idx_audit_created_result ON audit_operation_log(created_at, result);

CREATE TABLE run_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES iam_user(id),
    role_snapshot_json VARCHAR(1000000) NOT NULL,
    permission_snapshot_json VARCHAR(1000000) NOT NULL,
    permission_version BIGINT NOT NULL,
    config_release_id BIGINT NOT NULL REFERENCES cfg_release(id),
    execution_mode VARCHAR(20) NOT NULL CHECK (execution_mode IN ('DEMO','POC','PRODUCTION')),
    context_json VARCHAR(1000000) NOT NULL DEFAULT '{}',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_run_session_user_active ON run_session(user_id, active, created_at);

CREATE TABLE run_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL UNIQUE,
    session_id BIGINT NOT NULL REFERENCES run_session(id),
    parent_request_id BIGINT REFERENCES run_request(id),
    user_id BIGINT NOT NULL REFERENCES iam_user(id),
    trace_id VARCHAR(128) NOT NULL UNIQUE,
    idempotency_key VARCHAR(128) NOT NULL,
    scenario_id BIGINT REFERENCES flow_scenario(id),
    question VARCHAR(4000) NOT NULL,
    mode VARCHAR(20) NOT NULL CHECK (mode IN ('DEMO','POC','PRODUCTION')),
    status VARCHAR(32) NOT NULL CHECK (status IN ('PENDING','RUNNING','WAITING_INPUT','SHORT_CIRCUITED','BLOCKED','PARTIAL_SUCCESS','SUCCEEDED','FAILED','CANCELLATION_REQUESTED','CANCELLED','TIMED_OUT')),
    last_layer VARCHAR(4),
    termination_reason VARCHAR(128),
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE,
    UNIQUE(user_id, idempotency_key)
);
CREATE INDEX idx_run_request_session_created ON run_request(session_id, created_at);
CREATE INDEX idx_run_request_user_created ON run_request(user_id, created_at, id);
CREATE INDEX idx_run_request_status_created ON run_request(status, created_at);
