CREATE TABLE cfg_seed_import (
    source_code VARCHAR(64) PRIMARY KEY,
    source_path VARCHAR(512) NOT NULL,
    source_hash CHAR(64) NOT NULL,
    imported_rows INTEGER NOT NULL,
    imported_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE flow_scenario_role (
    scenario_id BIGINT NOT NULL REFERENCES flow_scenario(id),
    role_id BIGINT NOT NULL REFERENCES iam_role(id),
    allowed_modes_json VARCHAR(1000) NOT NULL,
    PRIMARY KEY(scenario_id, role_id)
);

CREATE TABLE flow_scenario_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id BIGINT NOT NULL REFERENCES flow_scenario(id),
    role_id BIGINT NOT NULL REFERENCES iam_role(id),
    case_code VARCHAR(64) NOT NULL UNIQUE,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ENABLED','DISABLED'))
);
CREATE INDEX idx_scenario_case_scenario_role ON flow_scenario_case(scenario_id, role_id);

CREATE TABLE flow_scenario_turn (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL REFERENCES flow_scenario_case(id),
    turn_no INTEGER NOT NULL CHECK (turn_no > 0),
    question VARCHAR(4000) NOT NULL,
    expected_status VARCHAR(32) NOT NULL,
    expected_last_layer VARCHAR(4) NOT NULL,
    expected_execution VARCHAR(32) NOT NULL,
    final_display VARCHAR(128),
    UNIQUE(case_id, turn_no)
);
