CREATE TABLE iam_identity_provider (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    provider_type VARCHAR(20) NOT NULL CHECK (provider_type IN ('TEST','OIDC','SAML','LDAP')),
    issuer VARCHAR(512),
    discovery_url VARCHAR(512),
    client_id VARCHAR(191),
    client_secret_id BIGINT REFERENCES ai_secret_ref(id),
    directory_endpoint VARCHAR(512),
    subject_claim VARCHAR(64) NOT NULL DEFAULT 'sub',
    username_claim VARCHAR(64) NOT NULL DEFAULT 'preferred_username',
    display_name_claim VARCHAR(64) NOT NULL DEFAULT 'name',
    org_claim VARCHAR(64) NOT NULL DEFAULT 'org',
    group_claim VARCHAR(64) NOT NULL DEFAULT 'groups',
    attribute_mapping_json VARCHAR(100000) NOT NULL DEFAULT '{}',
    jit_provisioning BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT','ENABLED','DISABLED')),
    version_no INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE iam_external_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES iam_user(id),
    identity_provider_id BIGINT NOT NULL REFERENCES iam_identity_provider(id),
    external_subject VARCHAR(191) NOT NULL,
    external_username VARCHAR(191) NOT NULL,
    attributes_hash CHAR(64) NOT NULL,
    last_synced_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_authenticated_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE','DISABLED','UNLINKED')),
    UNIQUE(identity_provider_id, external_subject)
);
CREATE INDEX idx_external_identity_user_status ON iam_external_identity(user_id, status);

CREATE TABLE iam_external_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_provider_id BIGINT NOT NULL REFERENCES iam_identity_provider(id),
    external_group_id VARCHAR(191) NOT NULL,
    group_name VARCHAR(191) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE','DISABLED')),
    last_synced_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE(identity_provider_id, external_group_id)
);

CREATE TABLE iam_external_group_role (
    external_group_id BIGINT NOT NULL REFERENCES iam_external_group(id),
    role_id BIGINT NOT NULL REFERENCES iam_role(id),
    valid_from TIMESTAMP WITH TIME ZONE,
    valid_to TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY(external_group_id, role_id)
);

CREATE TABLE iam_user_auth_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES iam_user(id),
    identity_provider_id BIGINT NOT NULL REFERENCES iam_identity_provider(id),
    external_subject_hash CHAR(64) NOT NULL,
    event_type VARCHAR(32) NOT NULL CHECK (event_type IN ('LOGIN','LOGOUT','FAILURE','TOKEN_REVOKED')),
    result VARCHAR(20) NOT NULL CHECK (result IN ('SUCCEEDED','FAILED','DENIED')),
    client_ip VARCHAR(64),
    user_agent_hash CHAR(64),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_auth_event_provider_time ON iam_user_auth_event(identity_provider_id, occurred_at);
CREATE INDEX idx_auth_event_user_time ON iam_user_auth_event(user_id, occurred_at);
