CREATE TABLE iam_role_org_scope (
    role_id BIGINT NOT NULL REFERENCES iam_role(id),
    org_id BIGINT NOT NULL REFERENCES iam_org(id),
    scope_type VARCHAR(20) NOT NULL CHECK (scope_type IN ('SELF','DESCENDANTS','EXACT')),
    effect VARCHAR(10) NOT NULL CHECK (effect IN ('ALLOW','DENY')),
    PRIMARY KEY(role_id, org_id, scope_type)
);

CREATE TABLE iam_role_metric_scope (
    role_id BIGINT NOT NULL REFERENCES iam_role(id),
    metric_id BIGINT NOT NULL REFERENCES meta_metric(id),
    detail_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    export_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    effect VARCHAR(10) NOT NULL CHECK (effect IN ('ALLOW','DENY')),
    PRIMARY KEY(role_id, metric_id)
);

CREATE TABLE iam_role_table_scope (
    role_id BIGINT NOT NULL REFERENCES iam_role(id),
    table_id BIGINT NOT NULL REFERENCES meta_data_table(id),
    detail_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    effect VARCHAR(10) NOT NULL CHECK (effect IN ('ALLOW','DENY')),
    PRIMARY KEY(role_id, table_id)
);

CREATE TABLE iam_role_field_scope (
    role_id BIGINT NOT NULL REFERENCES iam_role(id),
    field_id BIGINT NOT NULL REFERENCES meta_data_field(id),
    access_level VARCHAR(20) NOT NULL CHECK (access_level IN ('NONE','MASKED','FULL')),
    effect VARCHAR(10) NOT NULL CHECK (effect IN ('ALLOW','DENY')),
    PRIMARY KEY(role_id, field_id)
);

CREATE TABLE iam_user_data_override (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES iam_user(id),
    resource_type VARCHAR(20) NOT NULL CHECK (resource_type IN ('ORG','METRIC','TABLE','FIELD','FEATURE')),
    resource_id BIGINT NOT NULL,
    action_code VARCHAR(32) NOT NULL,
    effect VARCHAR(10) NOT NULL CHECK (effect IN ('ALLOW','DENY')),
    valid_from TIMESTAMP WITH TIME ZONE,
    valid_to TIMESTAMP WITH TIME ZONE,
    reason VARCHAR(500) NOT NULL,
    approval_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, resource_type, resource_id, action_code)
);
CREATE INDEX idx_user_override_active ON iam_user_data_override(user_id, resource_type, resource_id, valid_to);

CREATE TABLE sec_mandatory_denial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_type VARCHAR(20) NOT NULL,
    resource_id BIGINT NOT NULL,
    action_code VARCHAR(32) NOT NULL,
    reason_code VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ENABLED','DISABLED')),
    UNIQUE(resource_type, resource_id, action_code)
);

CREATE TABLE iam_permission_change_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES iam_user(id),
    old_version BIGINT NOT NULL,
    new_version BIGINT NOT NULL,
    reason VARCHAR(256) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, new_version)
);
CREATE INDEX idx_permission_change_user_time ON iam_permission_change_event(user_id, occurred_at);
