CREATE TABLE audit_workflow_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    business_type VARCHAR(64) NOT NULL,
    version_no INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT','ENABLED','DISABLED')),
    created_by BIGINT REFERENCES iam_user(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(code, version_no)
);

CREATE TABLE audit_workflow_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT NOT NULL REFERENCES audit_workflow_definition(id),
    step_no INTEGER NOT NULL CHECK (step_no > 0),
    name VARCHAR(128) NOT NULL,
    approval_mode VARCHAR(20) NOT NULL CHECK (approval_mode IN ('ANY','ALL','SEQUENTIAL')),
    approver_type VARCHAR(20) NOT NULL CHECK (approver_type IN ('USER','ROLE','ORG_OWNER','SECURITY_ADMIN')),
    approver_ref_id BIGINT,
    min_approvals INTEGER NOT NULL DEFAULT 1 CHECK (min_approvals > 0),
    reject_action VARCHAR(20) NOT NULL DEFAULT 'TERMINATE',
    timeout_hours INTEGER,
    UNIQUE(workflow_id, step_no)
);

CREATE TABLE audit_approval (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_no VARCHAR(64) NOT NULL UNIQUE,
    approval_type VARCHAR(64) NOT NULL,
    title VARCHAR(256) NOT NULL,
    applicant_id BIGINT NOT NULL REFERENCES iam_user(id),
    target_type VARCHAR(64) NOT NULL,
    target_id BIGINT NOT NULL,
    workflow_id BIGINT NOT NULL REFERENCES audit_workflow_definition(id),
    workflow_version INTEGER NOT NULL,
    current_step_no INTEGER NOT NULL,
    current_status VARCHAR(20) NOT NULL CHECK (current_status IN ('PENDING','APPROVED','REJECTED','CANCELLED','EXPIRED')),
    urgency VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_approval_status_submitted ON audit_approval(current_status, submitted_at);

CREATE TABLE audit_approval_candidate (
    approval_id BIGINT NOT NULL REFERENCES audit_approval(id),
    step_no INTEGER NOT NULL,
    approver_id BIGINT NOT NULL REFERENCES iam_user(id),
    candidate_source VARCHAR(32) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING','APPROVED','REJECTED','SKIPPED')),
    PRIMARY KEY(approval_id, step_no, approver_id)
);

CREATE TABLE audit_approval_action (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_id BIGINT NOT NULL REFERENCES audit_approval(id),
    step_no INTEGER NOT NULL,
    action VARCHAR(20) NOT NULL CHECK (action IN ('SUBMIT','APPROVE','REJECT','CANCEL','DELEGATE','TIMEOUT')),
    operator_id BIGINT NOT NULL REFERENCES iam_user(id),
    opinion VARCHAR(1000),
    from_status VARCHAR(20) NOT NULL,
    to_status VARCHAR(20) NOT NULL,
    delegated_from BIGINT REFERENCES iam_user(id),
    operated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_approval_action_instance ON audit_approval_action(approval_id, operated_at);
