CREATE TABLE meta_metric_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_id BIGINT NOT NULL REFERENCES meta_metric(id),
    table_id BIGINT NOT NULL REFERENCES meta_data_table(id),
    current_field_id BIGINT NOT NULL REFERENCES meta_data_field(id),
    previous_field_id BIGINT REFERENCES meta_data_field(id),
    filter_expression VARCHAR(2000),
    priority INTEGER NOT NULL DEFAULT 0,
    valid_from TIMESTAMP WITH TIME ZONE,
    valid_to TIMESTAMP WITH TIME ZONE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT','ENABLED','DISABLED')),
    UNIQUE(metric_id, table_id, priority)
);

CREATE TABLE meta_dimension_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dimension_id BIGINT NOT NULL REFERENCES meta_dimension(id),
    parent_id BIGINT REFERENCES meta_dimension_member(id),
    member_code VARCHAR(128) NOT NULL,
    member_name VARCHAR(256) NOT NULL,
    sort_no INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ENABLED','DISABLED')),
    UNIQUE(dimension_id, member_code)
);

CREATE TABLE meta_dimension_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dimension_id BIGINT NOT NULL REFERENCES meta_dimension(id),
    table_id BIGINT NOT NULL REFERENCES meta_data_table(id),
    field_id BIGINT NOT NULL REFERENCES meta_data_field(id),
    mapping_json VARCHAR(100000) NOT NULL DEFAULT '{}',
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT','ENABLED','DISABLED')),
    UNIQUE(dimension_id, table_id)
);

CREATE TABLE meta_synonym (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term VARCHAR(256) NOT NULL,
    canonical_term VARCHAR(256) NOT NULL,
    resource_type VARCHAR(32),
    resource_id BIGINT,
    priority INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ENABLED','DISABLED')),
    UNIQUE(term, canonical_term)
);

CREATE TABLE meta_recommendation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL REFERENCES iam_role(id),
    keyword VARCHAR(256) NOT NULL,
    question_template VARCHAR(1000) NOT NULL,
    priority INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ENABLED','DISABLED')),
    UNIQUE(role_id, question_template)
);

CREATE TABLE meta_lineage_edge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type VARCHAR(32) NOT NULL,
    source_id BIGINT NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_id BIGINT NOT NULL,
    relation_type VARCHAR(32) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ENABLED','DISABLED')),
    UNIQUE(source_type, source_id, target_type, target_id, relation_type)
);
CREATE INDEX idx_lineage_target ON meta_lineage_edge(target_type, target_id);
