CREATE TABLE flow_intent_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    intent_type VARCHAR(64) NOT NULL,
    keyword_pattern VARCHAR(1000) NOT NULL,
    priority INTEGER NOT NULL DEFAULT 0,
    terminal_layer VARCHAR(4) NOT NULL,
    handler_code VARCHAR(128) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT','ENABLED','DISABLED'))
);

ALTER TABLE flow_scenario ADD COLUMN intent_rule_id BIGINT;
ALTER TABLE flow_scenario ADD CONSTRAINT fk_scenario_intent FOREIGN KEY(intent_rule_id) REFERENCES flow_intent_rule(id);

CREATE TABLE flow_conversation_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(128) NOT NULL UNIQUE,
    config_value_json VARCHAR(100000) NOT NULL,
    value_type VARCHAR(32) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT','ENABLED','DISABLED'))
);

CREATE TABLE flow_layer_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    layer_code VARCHAR(4) NOT NULL UNIQUE,
    layer_name VARCHAR(128) NOT NULL,
    sequence_no INTEGER NOT NULL UNIQUE,
    handler_code VARCHAR(128) NOT NULL,
    provider_type VARCHAR(32) NOT NULL,
    timeout_seconds DECIMAL(6,2) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT','ENABLED','DISABLED'))
);

CREATE TABLE flow_scenario_asset (
    scenario_id BIGINT NOT NULL REFERENCES flow_scenario(id),
    data_source_id BIGINT NOT NULL REFERENCES meta_data_source(id),
    table_id BIGINT NOT NULL REFERENCES meta_data_table(id),
    metric_id BIGINT REFERENCES meta_metric(id),
    priority INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY(scenario_id, table_id, metric_id)
);

CREATE TABLE flow_quick_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id BIGINT NOT NULL REFERENCES flow_scenario(id),
    role_id BIGINT NOT NULL REFERENCES iam_role(id),
    button_name VARCHAR(128) NOT NULL,
    preset_question VARCHAR(1000) NOT NULL,
    tag VARCHAR(64),
    sort_no INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ENABLED','DISABLED')),
    UNIQUE(scenario_id, role_id, preset_question)
);

CREATE TABLE flow_dashboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    url VARCHAR(1000) NOT NULL,
    tag VARCHAR(64),
    status VARCHAR(20) NOT NULL CHECK (status IN ('ENABLED','DISABLED'))
);

CREATE TABLE flow_dashboard_role (
    dashboard_id BIGINT NOT NULL REFERENCES flow_dashboard(id),
    role_id BIGINT NOT NULL REFERENCES iam_role(id),
    PRIMARY KEY(dashboard_id, role_id)
);

CREATE TABLE flow_fixture (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    scenario_id BIGINT REFERENCES flow_scenario(id),
    fixture_json VARCHAR(1000000) NOT NULL,
    allowed_modes_json VARCHAR(1000) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ENABLED','DISABLED'))
);

CREATE TABLE flow_wording (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    scene VARCHAR(64) NOT NULL,
    language VARCHAR(16) NOT NULL,
    content VARCHAR(4000) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ENABLED','DISABLED'))
);
