from typing import Protocol,Any
class ModelProvider(Protocol):
 async def health_check(self)->dict: ...
 async def structured_generate(self,task:str,payload:dict)->dict: ...
class DataSourceProvider(Protocol):
 async def health_check(self)->dict: ...
 async def execute(self,sql:str,parameters:dict)->list[dict[str,Any]]: ...
 async def cancel(self,request_id:str)->bool: ...
